#+SETUPFILE: latexcss.theme
#+title: Munkres Topology, Chapter I
#+author: Aditya Yeleswarapu
#+date: <2026-01-23 Fri>
#+tags: :Topology

We can view topological spaces as a generalization of metric spaces or an extension of set theory. However we view them, the key feature of topological spaces is creation of certain "structure" over a set that allows us to talk about continuity of functions on the set without getting distracted by any other details.

** Basic definitions

#+begin_definition
A *Topology* on a set $X$ is a collection $\mathcal{T}$ of subsets of $X$ having the following properties:
1. $\emptyset$ and $X$ are in $\mathcal{T}$
2. $\mathcal{T}$ closed under arbitrary unions of elements
3. $\mathcal{T}$ closed under finite intersections of elements
#+end_definition

We call the set $X$, together with a topology $\mathcal{T}$ on it, a topological space. However practically $\mathcal{T}$ is clear from the context and we won't mention it.

$(X,\mathcal{T})$ a topological space.
- We say a subset $U$ of $X$ is an /open set/ of $X$ if $U \in \mathcal{T}$.
- Similarly, a subset $V$ of $X$ is a /closed set/ if its complement is open.

Observe that a set can be both open and closed (called clopen). Within topology, we encounter such sets aplenty. However, in geometry and analysis, we generally choose a topological space where that is not possible for sets other than $\emptyset$ and $X$ to avoid certain "pathological" cases.

Note that I used the word ‘closed’ to mean two different things in the definition and in defining "closed sets". I explain the former detail in set theory notes.

I am skipping some basic examples, but the gist is even small sets can have colossal number of topologies defined on them. We won't care about most of them. However, some of them are good to remember, as edge cases.

*Example.* $X$ a set. The power-set of $X$ forms a topology on $X$, called /discrete topology/. Observe that in this space, any set is both open and closed.

*Example.* On the opposite end, there is /indiscrete topology/. $X$ and $\emptyset$ are the only elements of this topology, so we also call it /trivial/ topology.

*Example.* Another example is the finite complement topology, where elements are complements of finite subsets of $X$. (Along with $\emptyset$ as rules would dictate)

** Comparison of Topologies

We can compare two topologies defined on a set.

#+begin_definition
$\mathcal{T}$ and $\mathcal{T'}$ be two topologies on $X$. If $\mathcal{T}\subset\mathcal{T'}$ (i.e. there are more sets in $\mathcal{T'}$ than $\mathcal{T}$) we say $\mathcal{T'}$ is /finer/ than $\mathcal{T}$. If the opposite, i.e. $T$ has more sets, we say $\mathcal{T'}$ is /coarser/.
#+end_definition

This is because $\mathcal{T}$ and $\mathcal{T'}$ are "spread" over the same set, only that finer one is present in a "finer" detail, while the "coarser" one is, as one would suspect, more "coarse".

Note that the order is partial here, since sometimes neither $\mathcal{T}\subset \mathcal{T'}$ nor $\mathcal{T'}\subset \mathcal{T}$ is true. Intuitively, to compare two "patches", they must overlap.

** Basis of a Topology

#+begin_definition
$(X,\mathcal{T})$ be a topological space. Collection $\mathit{B}$ of open subsets is a basis if all elements of $\mathcal{T}$ are union of some elements in $\mathit{B}$.
#+end_definition

Note that this means

1. For each $x\in X$ there is some basis element containing $x$
2. If $x$ is in intersection of two basis elements, there is another basis element inside that intersection

Munkres defines this in the opposite way.

Often, to talk about properties of a given topology, we only need to consider its basis.

To go in the opposite direction (i.e. to get a basis from given topology) we take a collection of sets $\mathit{F}$ such that for every open set $U$ in $\mathcal{T}$ and every element $x\in U$ there is a subset $H$ of $U$, $H \in \mathit{F}$ containing $x$.

In fact, this simplifies comparing topologies. When $\mathcal{T}$ is coarser than $\mathcal{T'}$ it means at any point $x$, if $B$ is some basis element of $\mathcal{T}$ containing $x$ there is some basis element $B'$ for $\mathcal{T'}$ which is within $B$. In other words, basis elements of finer topologies /are/ smaller!

On a similar note, a *sub-basis* $\mathit{S}$ for a topology on $X$ is a collection of subsets of $X$ whose union equals $X$ and finite intersections give the basis for the topology.

** Standard Topology

Although we gave examples of topologies before, we lacked the tools to define the most important, widely used topology - the topology defined by the metric. We are not in metric spaces book though, so we define more formally.

#+begin_definition
$\mathit{B}$ be collection of all subsets on the real line of the form

$$(a,b)=\{x\in \mathbb{R}|a < x < b\}$$

Topology generated by $\mathit{B}$ is the *standard topology* on $\mathbb{R}$.
#+end_definition

** Order Topology

In simply ordered sets, we can also define topology without the metrics. In the real case, these are simply the four types of intervals. i.e. those of the form $()$, $(]$, $[)$ and $[]$. We call the former open interval (referring to previous topology), and the last closed interval. We call the other two half-open.

/Order Topology/ allows open intervals as open sets. However, if there is a maxima or a minima, sets closed at that 'corner' are open too. Or rather, such intervals form the basis.

Note that order here can be anything. For example, there is dictionary order in $\mathbb{R}^{2}$ which is useful for nothing but defines a topology.

Note that on the real line, rays (i.e. intervals where one side is infinity) form a sub-basis for the order topology.


** Product Topology on X \times Y

We saw ways of obtaining topology from a set. Now we see how to create topology for new sets from old ones, particularly products and quotients. Current section is a "baby" version of this endeavor.

#+begin_definition
Let $X$ and $Y$ be two topological spaces. The product topology on $X\times Y$ is the topology having as basis the collection $\mathit{B}$ of all sets of the form $U\times V$ where $U$ is an open subset of $X$ and $V$ is an open subset of $Y$.
#+end_definition

We need this because the pairs $U\times V$ cannot form a topology. Especially unions. /We can also see product topology as the smallest possible topology that contains all the pairs $U \times V$./

Observe that if $\mathit{B}$ and $\mathit{C}$ are basis of $X\times Y$ then ordered pairs of their elements also form a (smaller) basis for $X\times Y$.

Now we construct a sub-basis for $X\times Y$. Take projection maps $\pi_{1}$ and $\pi_{2}$ from $X\times Y$ onto $X$ and $Y$ respectively. Take images of their inverse functions over open sets in $X$ and $Y$ (i.e. $U\times Y$ and $X\times V$). Unions of such sets form a sub-basis for $X\times Y$.


** Subspace Topology
